use_frameworks!

platform :ios, '8.0'

target 'LBOcModule_Example' do
  pod 'LBOcModule', :path => '../'

  target 'LBOcModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
